//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSharp.Sql.Azure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChainedHeader
    {
        public long ID { get; set; }
        public byte[] Hash { get; set; }
        public short Version { get; set; }
        public byte[] PreviousBlockHash { get; set; }
        public byte[] MerkleRoot { get; set; }
        public long Bits { get; set; }
        public System.DateTime Time { get; set; }
        public long Nonce { get; set; }
    }
}
