//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSharp.SqlServer.Azure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Input
    {
        public long ID { get; set; }
        public long TransactionID { get; set; }
        public byte[] TransactionHash { get; set; }
        public long TransactionIndex { get; set; }
        public byte[] Script { get; set; }
        public long SequenceNumber { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
